IF OBJECT_ID('Phone', 'U') IS NOT NULL DROP TABLE Phone
IF OBJECT_ID('Person', 'U') IS NOT NULL DROP TABLE Person

CREATE TABLE Person (
Id INT IDENTITY NOT NULL,
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(100) NOT NULL,
Gender VARCHAR(1) NOT NULL,
DocumentNumber VARCHAR(10) UNIQUE NOT NULL,
BirthDate DATE NOT NULL
PRIMARY KEY (Id),
CHECK (Gender in ('m', 'f'))
)
SELECT * FROM Person

CREATE TABLE Phone (
Id INT IDENTITY NOT NULL,
PersonId INT NOT NULL,
PhoneNumber VARCHAR(15) NOT NULL,
PRIMARY KEY (Id),
FOREIGN KEY (PersonId) REFERENCES Person(Id)
)
SELECT * FROM Phone